// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cod3rboy/contacts-book/ent/contact"
	"github.com/cod3rboy/contacts-book/ent/predicate"
	"github.com/cod3rboy/contacts-book/ent/schema"
)

// ContactUpdate is the builder for updating Contact entities.
type ContactUpdate struct {
	config
	hooks    []Hook
	mutation *ContactMutation
}

// Where appends a list predicates to the ContactUpdate builder.
func (cu *ContactUpdate) Where(ps ...predicate.Contact) *ContactUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetFirstName sets the "first_name" field.
func (cu *ContactUpdate) SetFirstName(s string) *ContactUpdate {
	cu.mutation.SetFirstName(s)
	return cu
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (cu *ContactUpdate) SetNillableFirstName(s *string) *ContactUpdate {
	if s != nil {
		cu.SetFirstName(*s)
	}
	return cu
}

// SetLastName sets the "last_name" field.
func (cu *ContactUpdate) SetLastName(s string) *ContactUpdate {
	cu.mutation.SetLastName(s)
	return cu
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (cu *ContactUpdate) SetNillableLastName(s *string) *ContactUpdate {
	if s != nil {
		cu.SetLastName(*s)
	}
	return cu
}

// ClearLastName clears the value of the "last_name" field.
func (cu *ContactUpdate) ClearLastName() *ContactUpdate {
	cu.mutation.ClearLastName()
	return cu
}

// SetGender sets the "gender" field.
func (cu *ContactUpdate) SetGender(c contact.Gender) *ContactUpdate {
	cu.mutation.SetGender(c)
	return cu
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (cu *ContactUpdate) SetNillableGender(c *contact.Gender) *ContactUpdate {
	if c != nil {
		cu.SetGender(*c)
	}
	return cu
}

// SetEmail sets the "email" field.
func (cu *ContactUpdate) SetEmail(s string) *ContactUpdate {
	cu.mutation.SetEmail(s)
	return cu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cu *ContactUpdate) SetNillableEmail(s *string) *ContactUpdate {
	if s != nil {
		cu.SetEmail(*s)
	}
	return cu
}

// ClearEmail clears the value of the "email" field.
func (cu *ContactUpdate) ClearEmail() *ContactUpdate {
	cu.mutation.ClearEmail()
	return cu
}

// SetMobileNumber sets the "mobile_number" field.
func (cu *ContactUpdate) SetMobileNumber(s string) *ContactUpdate {
	cu.mutation.SetMobileNumber(s)
	return cu
}

// SetNillableMobileNumber sets the "mobile_number" field if the given value is not nil.
func (cu *ContactUpdate) SetNillableMobileNumber(s *string) *ContactUpdate {
	if s != nil {
		cu.SetMobileNumber(*s)
	}
	return cu
}

// SetAddress sets the "address" field.
func (cu *ContactUpdate) SetAddress(s *schema.Address) *ContactUpdate {
	cu.mutation.SetAddress(s)
	return cu
}

// ClearAddress clears the value of the "address" field.
func (cu *ContactUpdate) ClearAddress() *ContactUpdate {
	cu.mutation.ClearAddress()
	return cu
}

// Mutation returns the ContactMutation object of the builder.
func (cu *ContactUpdate) Mutation() *ContactMutation {
	return cu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ContactUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ContactUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ContactUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ContactUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ContactUpdate) check() error {
	if v, ok := cu.mutation.FirstName(); ok {
		if err := contact.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Contact.first_name": %w`, err)}
		}
	}
	if v, ok := cu.mutation.Gender(); ok {
		if err := contact.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Contact.gender": %w`, err)}
		}
	}
	if v, ok := cu.mutation.MobileNumber(); ok {
		if err := contact.MobileNumberValidator(v); err != nil {
			return &ValidationError{Name: "mobile_number", err: fmt.Errorf(`ent: validator failed for field "Contact.mobile_number": %w`, err)}
		}
	}
	return nil
}

func (cu *ContactUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(contact.Table, contact.Columns, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.FirstName(); ok {
		_spec.SetField(contact.FieldFirstName, field.TypeString, value)
	}
	if value, ok := cu.mutation.LastName(); ok {
		_spec.SetField(contact.FieldLastName, field.TypeString, value)
	}
	if cu.mutation.LastNameCleared() {
		_spec.ClearField(contact.FieldLastName, field.TypeString)
	}
	if value, ok := cu.mutation.Gender(); ok {
		_spec.SetField(contact.FieldGender, field.TypeEnum, value)
	}
	if value, ok := cu.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
	}
	if cu.mutation.EmailCleared() {
		_spec.ClearField(contact.FieldEmail, field.TypeString)
	}
	if value, ok := cu.mutation.MobileNumber(); ok {
		_spec.SetField(contact.FieldMobileNumber, field.TypeString, value)
	}
	if value, ok := cu.mutation.Address(); ok {
		_spec.SetField(contact.FieldAddress, field.TypeJSON, value)
	}
	if cu.mutation.AddressCleared() {
		_spec.ClearField(contact.FieldAddress, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ContactUpdateOne is the builder for updating a single Contact entity.
type ContactUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContactMutation
}

// SetFirstName sets the "first_name" field.
func (cuo *ContactUpdateOne) SetFirstName(s string) *ContactUpdateOne {
	cuo.mutation.SetFirstName(s)
	return cuo
}

// SetNillableFirstName sets the "first_name" field if the given value is not nil.
func (cuo *ContactUpdateOne) SetNillableFirstName(s *string) *ContactUpdateOne {
	if s != nil {
		cuo.SetFirstName(*s)
	}
	return cuo
}

// SetLastName sets the "last_name" field.
func (cuo *ContactUpdateOne) SetLastName(s string) *ContactUpdateOne {
	cuo.mutation.SetLastName(s)
	return cuo
}

// SetNillableLastName sets the "last_name" field if the given value is not nil.
func (cuo *ContactUpdateOne) SetNillableLastName(s *string) *ContactUpdateOne {
	if s != nil {
		cuo.SetLastName(*s)
	}
	return cuo
}

// ClearLastName clears the value of the "last_name" field.
func (cuo *ContactUpdateOne) ClearLastName() *ContactUpdateOne {
	cuo.mutation.ClearLastName()
	return cuo
}

// SetGender sets the "gender" field.
func (cuo *ContactUpdateOne) SetGender(c contact.Gender) *ContactUpdateOne {
	cuo.mutation.SetGender(c)
	return cuo
}

// SetNillableGender sets the "gender" field if the given value is not nil.
func (cuo *ContactUpdateOne) SetNillableGender(c *contact.Gender) *ContactUpdateOne {
	if c != nil {
		cuo.SetGender(*c)
	}
	return cuo
}

// SetEmail sets the "email" field.
func (cuo *ContactUpdateOne) SetEmail(s string) *ContactUpdateOne {
	cuo.mutation.SetEmail(s)
	return cuo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (cuo *ContactUpdateOne) SetNillableEmail(s *string) *ContactUpdateOne {
	if s != nil {
		cuo.SetEmail(*s)
	}
	return cuo
}

// ClearEmail clears the value of the "email" field.
func (cuo *ContactUpdateOne) ClearEmail() *ContactUpdateOne {
	cuo.mutation.ClearEmail()
	return cuo
}

// SetMobileNumber sets the "mobile_number" field.
func (cuo *ContactUpdateOne) SetMobileNumber(s string) *ContactUpdateOne {
	cuo.mutation.SetMobileNumber(s)
	return cuo
}

// SetNillableMobileNumber sets the "mobile_number" field if the given value is not nil.
func (cuo *ContactUpdateOne) SetNillableMobileNumber(s *string) *ContactUpdateOne {
	if s != nil {
		cuo.SetMobileNumber(*s)
	}
	return cuo
}

// SetAddress sets the "address" field.
func (cuo *ContactUpdateOne) SetAddress(s *schema.Address) *ContactUpdateOne {
	cuo.mutation.SetAddress(s)
	return cuo
}

// ClearAddress clears the value of the "address" field.
func (cuo *ContactUpdateOne) ClearAddress() *ContactUpdateOne {
	cuo.mutation.ClearAddress()
	return cuo
}

// Mutation returns the ContactMutation object of the builder.
func (cuo *ContactUpdateOne) Mutation() *ContactMutation {
	return cuo.mutation
}

// Where appends a list predicates to the ContactUpdate builder.
func (cuo *ContactUpdateOne) Where(ps ...predicate.Contact) *ContactUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ContactUpdateOne) Select(field string, fields ...string) *ContactUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Contact entity.
func (cuo *ContactUpdateOne) Save(ctx context.Context) (*Contact, error) {
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ContactUpdateOne) SaveX(ctx context.Context) *Contact {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ContactUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ContactUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ContactUpdateOne) check() error {
	if v, ok := cuo.mutation.FirstName(); ok {
		if err := contact.FirstNameValidator(v); err != nil {
			return &ValidationError{Name: "first_name", err: fmt.Errorf(`ent: validator failed for field "Contact.first_name": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.Gender(); ok {
		if err := contact.GenderValidator(v); err != nil {
			return &ValidationError{Name: "gender", err: fmt.Errorf(`ent: validator failed for field "Contact.gender": %w`, err)}
		}
	}
	if v, ok := cuo.mutation.MobileNumber(); ok {
		if err := contact.MobileNumberValidator(v); err != nil {
			return &ValidationError{Name: "mobile_number", err: fmt.Errorf(`ent: validator failed for field "Contact.mobile_number": %w`, err)}
		}
	}
	return nil
}

func (cuo *ContactUpdateOne) sqlSave(ctx context.Context) (_node *Contact, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(contact.Table, contact.Columns, sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Contact.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contact.FieldID)
		for _, f := range fields {
			if !contact.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != contact.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.FirstName(); ok {
		_spec.SetField(contact.FieldFirstName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.LastName(); ok {
		_spec.SetField(contact.FieldLastName, field.TypeString, value)
	}
	if cuo.mutation.LastNameCleared() {
		_spec.ClearField(contact.FieldLastName, field.TypeString)
	}
	if value, ok := cuo.mutation.Gender(); ok {
		_spec.SetField(contact.FieldGender, field.TypeEnum, value)
	}
	if value, ok := cuo.mutation.Email(); ok {
		_spec.SetField(contact.FieldEmail, field.TypeString, value)
	}
	if cuo.mutation.EmailCleared() {
		_spec.ClearField(contact.FieldEmail, field.TypeString)
	}
	if value, ok := cuo.mutation.MobileNumber(); ok {
		_spec.SetField(contact.FieldMobileNumber, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Address(); ok {
		_spec.SetField(contact.FieldAddress, field.TypeJSON, value)
	}
	if cuo.mutation.AddressCleared() {
		_spec.ClearField(contact.FieldAddress, field.TypeJSON)
	}
	_node = &Contact{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{contact.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
